---
# Install MongoDB on a Debian-based distro using apt
#
# Author: Valentin DAMBRINE <val.dambrine97@gmail.com>
#
# Date: March, 07th 2020

- hosts: mongo
  remote_user: root
  tasks:
    - name: Add MongoDB apt key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.2.asc
        state: present

    - name: Add MongoDB repository
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse
        state: present

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present